Repository NOAA-OWP/hydrotools, pull requests merged in 2021-04, with the labels that each got.

#55 Add MSE and NSE methods to metrics subpackage
  python/metrics/evaluation_tools/metrics/metrics.py
  python/metrics/setup.py
  python/metrics/tests/test_metrics.py
  setup.py
Labels: enhancement

#61 Add metrics README
  python/metrics/README.md
Labels: documentation

#63 Add `README.md` to events subpackage
  python/events/README.md
Labels: documentation

#64 Add nwis_client README.md
  python/nwis_client/README.md
Labels: documentation

#66 Major Refactor and Feature Additions to GCP Client
  .gitignore
  python/gcp_client/README.md
  python/gcp_client/hydrotools/gcp_client/gcp.py
  python/gcp_client/pytest.ini
  python/gcp_client/setup.py
  python/gcp_client/tests/test_gcp.py
Labels: enhancement

#67 _restclient utilities module: add Alias and AliasGroup classes
  docs/hydrotools._restclient._restclient.rst
  docs/hydrotools._restclient.rst
  docs/hydrotools._restclient.utilities.rst
  python/_restclient/hydrotools/_restclient/__init__.py
  python/_restclient/hydrotools/_restclient/_iterable_nonstring.py
  python/_restclient/hydrotools/_restclient/utilities.py
  python/_restclient/setup.py
  python/_restclient/tests/test_iterable_nonstring.py
  python/_restclient/tests/test_utilities.py
Labels: enhancement

#71 nwis_client now depends on _restclient from pypi
  python/nwis_client/setup.py
Labels: bug
