Repository NOAA-OWP/hydrotools, pull requests merged in 2021-02, with the labels that each got.

#31 gh-pages CI deployment
  .github/workflows/deploy-gh-pages.yml
Labels: documentation

#32 Update Readme with Categorical Notes
  README.md
Labels: documentation

#33 Update gitflow documentation
  gitflow.md
Labels: documentation

#34 Fix gh-pages deployment gh-action
  .github/workflows/deploy-gh-pages.yml
Labels: bug

#42 Add option to shift event start times to local minimum
  python/events/evaluation_tools/events/event_detection/decomposition.py
  python/events/setup.py
  python/events/tests/test_decomposition.py
Labels: enhancement

#44 Raise exceptions for bad time series index in event detection
  python/events/evaluation_tools/events/event_detection/decomposition.py
  python/events/setup.py
  python/events/tests/test_decomposition.py
  setup.py
Labels: enhancement

#45 Light Event Detection Refactor
  python/events/evaluation_tools/events/event_detection/decomposition.py
  python/events/setup.py
  python/events/tests/test_decomposition.py
  setup.py
Labels: bug, enhancement

#47 Add Event Detection to github pages
  docs/evaluation_tools.events.event_detection.decomposition.rst
  docs/evaluation_tools.events.event_detection.rst
  docs/index.rst
  python/events/evaluation_tools/events/event_detection/decomposition.py
Labels: documentation
